# Generated by Django 3.2.2 on 2021-05-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='henesysuser',
            name='temp',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
